### ISSUE TITLE
Not selling what I was told to, resulted in finding some bug where it marks the lowest value thing?

### ISSUE THREAD

**Issue by Roobotics** [riceisacereal/MinimumQuotaFinder#13]
![20240223014210_1](https://github.com/riceisacereal/MinimumQuotaFinder/assets/6250768/64efec89-8e70-4a33-876e-a66cc8a5d175)
As you see I've already met the quota with 136/130, however:
![20240223014807_1](https://github.com/riceisacereal/MinimumQuotaFinder/assets/6250768/e6ebe43d-5924-45b4-a3e9-f93e0e83dfdc)
Is it highlighting this because it's the lowest value item present?
It wanted me to sell my 'Remote' for 38, but I sold another item for 45 or so.
I haven't noticed it doing this when I sell exactly what I'm told to, but improvising seems to bug something out.

We really need a way to exclude items, or save them for 'very last'. They are scrap of course, but often scrap with other purposes! Laser and Remote being good examples of this, as many mods tend to make use of them. Laser can detonate mines, remote can flash radar booster, etc!

**Comment by riceisacereal** [comment]
Good catch! @Luesewr looked into it and we believe it's because we forgot to check the case where you've already sold over the quota, which then returns the lowest value item in our greedy approximation. A rather stupid oversight honestly, we'll try to patch it immediately.

We haven't had much time lately to work on the mod, but hopefully in the next weeks or so we can go back to implementing custom configurations. Thank you for your support!

**Comment by Roobotics** [comment]
It's completely understandable, it's an excellent mod, just being able to visually see what needs to be sold, is a very nice QoL feature while selling, and makes me want to use less of the mods like 'sell at terminal' because unless you are holding what you want to keep or specifying exact items, whoops! With this it's a lot easier to at least warn folks not to sell certain things if possible, etc.

Maybe in the future we can somehow 'paint' or 'flag' no-sell items with a special keybind or something, but I realize it needs to be excluded from all current clients, else it's a visual desync.

**Comment by riceisacereal** [comment]
I'm glad you are enjoying our mod so much! That is actually a good point you've brought up. As of right now our mod is still a client-side mod, we will need to think about whether we want to change that to allow for automatic syncing but require everyone to have the mod, or still have it as a client-side mod but then everyone will have to manually communicate what to exclude. We've never dealt with server-sided code yet so that would also be new to us!

**Comment by Roobotics** [comment]
Awesome, thanks for looking into this and the quick responses btw! I initially questioned if this was a bug or I failed a RTFM test along the way, and it was something intentional. But glad that helped find an underlying issue. 

After having used the mod for a bit, I'll give some feedback as a possible 'feature request'. 

Thanks for all the work you've put into this. Folks I've shared my custom packs with, and the mod, are also impressed by how it works/looks, and how it speeds up the tedium of selling the 'right amount.' while keeping the process otherwise vanilla.

**Comment by riceisacereal** [comment]
Thank you for the kind words <3 A good tool comes with a detailed manual, but a great tool doesn't even need one. Any "stupid" issue reflects a lack in effective communication somewhere and is always a possible area of improvement.

In the initial stages of development I did indeed question whether people would still want a mod like this when there are already auto-selling mods, since I started out wanting to improve exactly what you've described, I thought it would be stupid to still keep the manual delivering + selling. @Luesewr said that our mod still keeps the vibe of the game and there are definitely people who appreciate that, and you've proved his point! :^) Thanks again for your support, we love to see people enjoy our tools!

**Comment by Roobotics** [comment]
I'd be inclined to agree! I had another play session with a group just tonight, a pack I've created with at this time, 101 mods(not exaggerating) that I've tried my hardest to keep everything compatible, not take performance hits, add balance, and some new (balanced) varieties, along with QoL features that don't break existing dynamics, and that includes checking **every** config file before and after playtesting where possible!

Your selling mod once again got direct and unprompted praise btw, for "Keeping the danger of being at the Company building and getting 'Jeb'ed' if you aren't careful. While also making it less tedious." Primarily a combination of your mod as well as the "SellTracker" mod so you have a total at the counter to look at instead of a floating UI element. It's a really good combo for not getting confused.
